replicaCount: 2
 
image:
  repository: josetamayo/bootcampclt-api
  tag: "1.1"
  pullPolicy: IfNotPresent
app:
  containerPort: 8080
  env:
    aspnetcoreEnvironment: Development
    applicationName: API-BOOTCAMP-TAMAYO

 
service:
  type: NodePort
  port: 80
  targetPort: 8080
 
postgres:
  host: postgres-svc
  port: 5432
  database: hardwareCLT
  username: postgres
  password: "a.123456"   # Para demo local. En equipos reales, no commitear.